// seed.ts — mock content for nihon101 (frontend seed; single source of truth for placeholders).
// Ported from the design-tool bundle (ui-mocks/decoded-v2/data.jsx). Posts have EN + JP
// titles, real-ish bodies, author refs, category, and an image placeholder hue/label.
// When the backend lands, this shape mirrors the DB rows so the two can be wired up.

export const CATEGORIES = [
  { slug: 'culture',     en: 'Culture',     jp: '文化',   kanji: '文', tint: 'rose' },
  { slug: 'food',        en: 'Food',        jp: '食',     kanji: '食', tint: 'amber' },
  { slug: 'travel',      en: 'Travel',      jp: '旅',     kanji: '旅', tint: 'blue' },
  { slug: 'language',    en: 'Language',    jp: '言葉',   kanji: '言', tint: 'lilac' },
  { slug: 'animation',   en: 'Animation',   jp: 'アニメ', kanji: '画', tint: 'peach' },
  { slug: 'philosophy',  en: 'Philosophy',  jp: '哲学',   kanji: '哲', tint: 'sage' },
  { slug: 'history',     en: 'History',     jp: '歴史',   kanji: '史', tint: 'clay' },
  { slug: 'fashion',     en: 'Fashion',     jp: 'ファッション', kanji: '装', tint: 'mauve' },
  { slug: 'news',        en: 'News',        jp: '今日のこと', kanji: '新', tint: 'sky' },
];

export const AUTHORS = [
  { slug: 'mio-tanaka',     en: 'Mio Tanaka',     jp: '田中 美緒', city: 'Tokyo',    role: 'Editor-in-chief',
    bio_en: 'Editor of nihon101. Writes about everyday objects, cafés, and the geometry of small rooms.',
    bio_jp: '東京在住。喫茶店と日常の幾何学について書く。', initials: 'MT', tint: 'rose', posts: 14 },
  { slug: 'kenji-wada',     en: 'Kenji Wada',     jp: '和田 健司', city: 'Niigata',  role: 'Travel writer',
    bio_en: 'Travel writer based in snow country. Rides slow trains, eats fast soba.',
    bio_jp: '新潟在住。鈍行列車と早食いの蕎麦が好き。', initials: 'KW', tint: 'blue', posts: 22 },
  { slug: 'aiko-hayashi',   en: 'Aiko Hayashi',   jp: '林 愛子',   city: 'Osaka',    role: 'Food writer',
    bio_en: 'Osaka-based food writer. Convenience stores, kissaten, and the politics of seasoning.',
    bio_jp: '大阪在住。コンビニ、喫茶店、そして味付けの政治。', initials: 'AH', tint: 'amber', posts: 18 },
  { slug: 'daniel-reeves',  en: 'Daniel Reeves',  jp: 'ダニエル・リーヴス', city: 'Kyoto', role: 'Contributing writer',
    bio_en: 'Translator and essayist in Kyoto. Writes about animation, light, and bathhouses.',
    bio_jp: '京都在住。アニメと光と銭湯について書く翻訳家。', initials: 'DR', tint: 'peach', posts: 9 },
  { slug: 'sora-nakamura',  en: 'Sora Nakamura',  jp: '中村 空',   city: 'Kanazawa', role: 'Essayist',
    bio_en: 'Essayist in Kanazawa. Onsen towns, mottainai, and the long winter.',
    bio_jp: '金沢在住。温泉町、もったいない、そして長い冬。', initials: 'SN', tint: 'sage', posts: 11 },
  { slug: 'yuki-mori',      en: 'Yuki Mori',      jp: '森 由紀',   city: 'Sendai',   role: 'Culture writer',
    bio_en: 'Writes about festivals, shrines, and the strange calm of a Tuesday in Tohoku.',
    bio_jp: '仙台在住。祭り、神社、東北の火曜日の静けさについて。', initials: 'YM', tint: 'mauve', posts: 16 },
  { slug: 'ren-takahashi',  en: 'Ren Takahashi',  jp: '高橋 蓮',   city: 'Yokohama', role: 'Music writer',
    bio_en: 'City pop, jazz kissa, and the records my father wouldn’t throw away.',
    bio_jp: '横浜在住。シティポップ、ジャズ喫茶、父が捨てなかったレコード。', initials: 'RT', tint: 'sky', posts: 8 },
  { slug: 'hana-kobayashi', en: 'Hana Kobayashi', jp: '小林 花',   city: 'Kyoto',    role: 'Fashion writer',
    bio_en: 'Kimono, vintage, and what people in Kyoto actually wear on a cold morning.',
    bio_jp: '京都在住。着物、古着、寒い朝に京都の人が本当に着るもの。', initials: 'HK', tint: 'rose', posts: 19 },
  { slug: 'taro-ishida',    en: 'Taro Ishida',    jp: '石田 太郎', city: 'Hiroshima', role: 'History writer',
    bio_en: 'Local historian. The past, but only the parts you can still walk to.',
    bio_jp: '広島在住。郷土史家。今も歩いて行ける過去だけを書く。', initials: 'TI', tint: 'clay', posts: 24 },
  { slug: 'mei-fujimoto',   en: 'Mei Fujimoto',   jp: '藤本 芽衣', city: 'Nagoya',   role: 'Food writer',
    bio_en: 'Diners, depachika, and the architecture of a perfect convenience-store lunch.',
    bio_jp: '名古屋在住。食堂、デパ地下、完璧なコンビニ昼食の建築。', initials: 'MF', tint: 'amber', posts: 13 },
  { slug: 'jun-okada',      en: 'Jun Okada',      jp: '岡田 純',   city: 'Sapporo',  role: 'Animation writer',
    bio_en: 'Frames, in-betweens, and why a single cut can hold a whole season.',
    bio_jp: '札幌在住。原画、中割り、一カットが一季節を抱える理由。', initials: 'JO', tint: 'lilac', posts: 7 },
  { slug: 'nao-shimizu',    en: 'Nao Shimizu',    jp: '清水 奈緒', city: 'Okinawa',  role: 'Travel writer',
    bio_en: 'Islands, ferries, and the long way around. Usually the long way around.',
    bio_jp: '沖縄在住。島、フェリー、そして遠回り。たいてい遠回り。', initials: 'NS', tint: 'blue', posts: 15 },
];

export const POSTS = [
  {
    slug: 'quiet-geometry-of-a-kissaten',
    title_en: 'The quiet geometry of a kissaten',
    title_jp: '喫茶店の静かな幾何学',
    kicker_en: 'Tokyo, 2 p.m.',
    kicker_jp: '東京、午後二時',
    category: 'culture',
    author: 'mio-tanaka',
    date: 'Mar 14, 2026',
    readMins: 7,
    featured: true,
    cover: { hue: 'cream',  label: 'kissaten interior' },
    excerpt_en: 'There is a particular angle of afternoon light, sometime around two, when a Showa-era coffee shop arranges itself into a quiet, repeatable shape — a logic of saucers, ashtrays, and the slow stir of a long spoon.',
    excerpt_jp: '昭和の喫茶店には、午後二時ごろの光と、長いスプーンの音が作る、静かな幾何学がある。',
    body_en: [
      'There is a particular angle of afternoon light, sometime around two, when a Showa-era kissaten arranges itself into a quiet, repeatable shape. The smoke rises in a single line. The saucer ticks against the cup. A salaryman closes his eyes for a moment that is not quite a nap.',
      'Kissaten — 喫茶店 — translates as "tea-drinking shop", but it has always meant something more like "the place to be slowly". The chairs are too low, on purpose. The siphon coffee takes too long, on purpose. The newspaper rack is full of yesterday\'s news, and that is also on purpose.',
      'In a city that runs on the seven-second efficiency of the convenience store, the kissaten remains the most quietly radical room in Tokyo. It is the only place where doing nothing for an hour does not require an apology.',
      'I have a list of them. I will not give you the list.',
    ],
    likes: 1240, saved: false,
  },
  {
    slug: 'snow-country-winter-echigo',
    title_en: 'Snow country: a winter in Echigo-Yuzawa',
    title_jp: '雪国 — 越後湯沢の冬',
    kicker_en: 'Niigata',
    kicker_jp: '新潟',
    category: 'travel',
    author: 'kenji-wada',
    date: 'Feb 28, 2026',
    readMins: 11,
    featured: true,
    cover: { hue: 'blue', label: 'snowfall on cedar' },
    excerpt_en: 'The train comes out of the long tunnel and the bottom of the night turns white. Kawabata\'s opening line is the only honest weather report Niigata has ever received.',
    excerpt_jp: '長いトンネルを抜けると雪国であった。川端の一文は、新潟の唯一の正直な天気予報である。',
    body_en: [
      'The train comes out of the long tunnel and the bottom of the night turns white.',
      'Kawabata\'s opening line is, even now, the only honest weather report Niigata has ever received. There is the tunnel, and then there is the white. There is no transition.',
      'I came to Echigo-Yuzawa for the eighth winter in a row. I have stopped pretending that I am here to ski.',
    ],
    likes: 892, saved: true,
  },
  {
    slug: 'how-to-slurp-soba',
    title_en: 'How to slurp soba without apology',
    title_jp: '蕎麦のすすり方',
    kicker_en: 'A short manifesto',
    kicker_jp: '小さな宣言',
    category: 'food',
    author: 'aiko-hayashi',
    date: 'Mar 02, 2026',
    readMins: 4,
    featured: false,
    cover: { hue: 'amber', label: 'soba bowl' },
    excerpt_en: 'Foreign manners are not Japanese manners. You will not be forgiven for slurping, but you will be forgiven for not understanding why nobody minds.',
    excerpt_jp: '外国の礼儀は日本の礼儀ではない。',
    likes: 2310, saved: false,
  },
  {
    slug: 'untranslatable-komorebi',
    title_en: 'The untranslatable: 木漏れ日',
    title_jp: '訳せない言葉 — 木漏れ日',
    kicker_en: 'Language column #4',
    kicker_jp: '言葉のコラム その四',
    category: 'language',
    author: 'mio-tanaka',
    date: 'Feb 22, 2026',
    readMins: 6,
    featured: false,
    cover: { hue: 'sage', label: 'sunlight through leaves' },
    excerpt_en: 'Komorebi — sunlight as filtered by trees. It is not poetry; it is a noun. The English language has decided, for reasons that seem urgent to no one, not to have a word for this.',
    excerpt_jp: '木漏れ日は詩ではなく名詞である。',
    likes: 3010, saved: true,
  },
  {
    slug: 'yokai-in-the-konbini',
    title_en: 'Yokai in the convenience store aisle',
    title_jp: 'コンビニの妖怪たち',
    kicker_en: 'Modern hauntings',
    kicker_jp: '現代の怪',
    category: 'culture',
    author: 'daniel-reeves',
    date: 'Feb 18, 2026',
    readMins: 9,
    featured: false,
    cover: { hue: 'lilac', label: 'konbini at night' },
    excerpt_en: 'The kappa has moved indoors. The kitsune now works the night shift. The fluorescent ghosts of Japanese folklore have, like the rest of us, simply taken jobs at the 7-Eleven.',
    excerpt_jp: '河童は屋内に移り、狐は夜勤に出る。',
    likes: 1567, saved: false,
  },
  {
    slug: 'riding-the-yamanote-at-2am',
    title_en: 'Riding the Yamanote at 2 a.m.',
    title_jp: '深夜二時の山手線',
    kicker_en: 'Field notes',
    kicker_jp: 'フィールドノート',
    category: 'travel',
    author: 'kenji-wada',
    date: 'Feb 11, 2026',
    readMins: 5,
    featured: false,
    cover: { hue: 'sky', label: 'platform at night' },
    excerpt_en: 'You can\'t. The trains stop at midnight. That is the article. The longer version is a meditation on what a city does in the hours when it is not allowed to move.',
    excerpt_jp: '終電のあと、街は何をしているのか。',
    likes: 678, saved: false,
  },
  {
    slug: 'tamago-sando-manifesto',
    title_en: 'The 7-Eleven tamago sando manifesto',
    title_jp: 'コンビニのたまごサンド宣言',
    kicker_en: 'A defense',
    kicker_jp: '弁護',
    category: 'food',
    author: 'aiko-hayashi',
    date: 'Feb 05, 2026',
    readMins: 6,
    featured: false,
    cover: { hue: 'peach', label: 'egg sandwich' },
    excerpt_en: 'The American food writer who called this sandwich "surprising" should not be permitted, by treaty, to write about Japan for a period of two years.',
    excerpt_jp: '「驚くべき」と書いた外国人記者には、二年間の執筆禁止を提案する。',
    likes: 4520, saved: true,
  },
  {
    slug: 'wabi-sabi-beyond-aesthetic',
    title_en: 'Wabi-sabi beyond the aesthetic',
    title_jp: '侘寂 — 美学を超えて',
    kicker_en: 'Long read',
    kicker_jp: '長い読みもの',
    category: 'philosophy',
    author: 'sora-nakamura',
    date: 'Jan 30, 2026',
    readMins: 14,
    featured: false,
    cover: { hue: 'clay', label: 'cracked ceramic' },
    excerpt_en: 'When the West borrowed wabi-sabi, it kept the cracked teacup and threw out the ethics. This is a small attempt to bring the ethics back.',
    excerpt_jp: '西洋は欠けた茶碗を借りて、倫理を返さなかった。',
    likes: 2140, saved: false,
  },
  {
    slug: 'ghibli-taught-me-about-light',
    title_en: 'What Ghibli taught me about light',
    title_jp: 'ジブリと光のはなし',
    kicker_en: 'Animation essay',
    kicker_jp: 'アニメ評',
    category: 'animation',
    author: 'daniel-reeves',
    date: 'Jan 22, 2026',
    readMins: 8,
    featured: false,
    cover: { hue: 'amber', label: 'painted window light' },
    excerpt_en: 'In Miyazaki\'s films, light is never simply present. It is poured, decanted, refused, and on at least one occasion, served in a cup.',
    excerpt_jp: '宮崎の映画では、光は注がれ、断られ、ときに茶碗に出される。',
    likes: 3870, saved: false,
  },
  {
    slug: 'letters-from-an-onsen-town',
    title_en: 'Letters from an onsen town',
    title_jp: '温泉町からの便り',
    kicker_en: 'Postcard #2',
    kicker_jp: '便り その二',
    category: 'travel',
    author: 'sora-nakamura',
    date: 'Jan 14, 2026',
    readMins: 7,
    featured: false,
    cover: { hue: 'rose', label: 'steam over water' },
    excerpt_en: 'In a small onsen town in winter, the only sound between 9 p.m. and 6 a.m. is the bath water moving. I have begun to understand why people leave Tokyo.',
    excerpt_jp: '冬の小さな温泉町、夜九時から朝六時まで聞こえるのは湯の音だけだ。',
    likes: 1290, saved: false,
  },
  {
    slug: 'combini-bento-architecture',
    title_en: 'The architecture of a combini bento',
    title_jp: 'コンビニ弁当の建築',
    kicker_en: 'Diagrammed',
    kicker_jp: '図解',
    category: 'food',
    author: 'mio-tanaka',
    date: 'Jan 08, 2026',
    readMins: 5,
    featured: false,
    cover: { hue: 'peach', label: 'bento compartments' },
    excerpt_en: 'A bento is not a meal. It is a floor plan. The rice is the foundation; the umeboshi is the load-bearing wall.',
    excerpt_jp: '弁当は食事ではなく、間取りである。',
    likes: 980, saved: false,
  },
  {
    slug: 'mottainai-ethics',
    title_en: 'Mottainai: the ethics of not wasting',
    title_jp: 'もったいないの倫理',
    kicker_en: 'Philosophy',
    kicker_jp: '哲学',
    category: 'philosophy',
    author: 'aiko-hayashi',
    date: 'Dec 28, 2025',
    readMins: 10,
    featured: false,
    cover: { hue: 'sage', label: 'folded cloth' },
    excerpt_en: 'Mottainai is the only Japanese word my grandmother ever used in English. She used it for everything: cold tea, daylight, a sleeping cat.',
    excerpt_jp: 'もったいないは、祖母が英語の中で使った唯一の日本語だった。',
    likes: 2670, saved: true,
  },
];

export const NIHON_DATA = { CATEGORIES, AUTHORS, POSTS };
export default NIHON_DATA;
